distro: Xenial

branches:
  only:
    - master

notifications:
  on_success: never
  on_failure: change

os:
  - linux

language: node_js

node_js:
 - "10"

before_install:
  - cd dev
  - npm i -g vsce
  - npm i

  - echo "Working directory $(pwd)"
  - echo "TSC $(./node_modules/typescript/bin/tsc --version)"
  # List all our source files, this way we can see if there are
  # any more issues due to git not handling case-sensitive fileames very well
  - ls -AR src/
  # Make sure compilation will succeed ( vsce package won't show the compilation failures >:( )
  - npm run compile

script:
  - vsce package

after_success:
  # Go back to top level, then copy the vsix we just built to .
  - cd ..
  - ls -a
  # Checkout the 'build' branch, which will have nothing in it except the newest build.
  # We're going to replace that with the build we just created.
  - git config user.email "travis@travis.ibm.com"
  - git config user.name "Travis-CI"
  - git fetch origin build:build
  - git reset --hard build
  - git checkout build
  # Copy in the build artifact AFTER we do the hard reset
  - cp dev/*.vsix .
  - git add -f *.vsix
  - git status
  # This will make a commit with a name like "New build @ 6f1ea87 by Tim Etchells - further travis improvements"
  - export build_date="$(date +'%F %H:%M')"
  - export commit_info="$(git log master -1 --pretty='%h by %an - %s')"
  - 'git commit -m "New build @ $build_date" -m "$commit_info"'
  - git push origin build