distro: Xenial

branches:
  only:
    - master

notifications:
  on_success: change
  on_failure: change

os:
  - linux

language: node_js

node_js:
 - "10"

before_install:
  # Copy the LICENSE into the extension directory, so it is included in the build
  - cp -v LICENSE.* dev

  - cd dev
  - npm i -g vsce
  - npm i

  # Make sure compilation will succeed ( vsce package won't show the compilation failures >:( )
  # Fail the build if compile fails
  - npm run compile
  # Run the linter, but don't let that block the build (might change this later)
  - npm run lint-f

script:
  - vsce package

after_success:
  - cd ..
  - ./publish.sh

#before_deploy:
#  # cwd back to repo root
#  - cd ..
#  - cp -v dev/*.vsix .
#  - export artifact_name="$(basename *.vsix)"
#  - git config --local user.name "tetchel"
#  - git config --local user.email "timetchells@ibm.com"
#  - export TRAVIS_TAG="nightly-$(date +'%F_%H-%M_%Z')"
#  - git tag $TRAVIS_TAG
#
#deploy:
#  on:
#    branch: master
#    condition: $TRAVIS_EVENT_TYPE = cron
#  provider: releases
#  api_key: ???
#  file: $artifact_name
#  skip_cleanup: true