env:
  # Remove when 19.1 is done and tagged
  - release=true

branches:
  only:
  - master
  - travis-test

notifications:
  email:
    recipients:
      - timetchells@ibm.com
      # - devexbld@us.ibm.com
    on_success: change
    on_failure: change

os:
- linux

language: node_js
node_js:
- '10'

before_install:
- cd dev/
- ../script/before-install.sh

script:
- vsce package

after_success:
# copy the vsix to the script dir and cd into it
- export artifact_name="$(basename *.vsix)"
- mv -v $artifact_name ../script/
- cd ../script/
# will exit immediately if not a deploy build
- ./deploy.sh || >&2 echo "Deploy failed!"